version: 2
updates:
  # Enable version updates for Go modules only
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"  # เปลี่ยนจาก weekly เป็น monthly
      day: 1
      time: "09:00"
      timezone: "Asia/Bangkok"
    open-pull-requests-limit: 3  # ลดจำนวน PR ที่เปิดพร้อมกัน
    reviewers:
      - "callmetos"
    assignees:
      - "callmetos"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
    ignore:
      # Ignore major version updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Ignore specific packages if needed
      # - dependency-name: "github.com/gin-gonic/gin"
